### ISSUE TITLE
GitHub Actions: Transitioning from Node 16 to Node 20

### ISSUE THREAD

**Issue by tlipkadci** [BeaconBrigade/package-json-version#1]
Hello, 

Github plans to migrate all activities to run on node 20 by spring 2024. Please upgrade project to node@20. 

More information:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: beaconbrigade/package-json-version@v0.3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by BeaconBrigade** [comment]
Hey should be fixed in ddab5179c8ab006cc6b9b1a54c61cc35f0e900d4. Thanks for letting me know

**Comment by arkadijs** [comment]
Could we please have a v0.4 tag for this fix?

**Comment by BeaconBrigade** [comment]
@arkadijs I just published a release and fixed the version numbers. Let me know if anything needs fixing.

**Comment by arkadijs** [comment]
Hi, doesn't work for me:
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: beaconbrigade/package-json-version@v0.3.1.

The v0.3.1 release is at 678dd2c which is pre-Node-20 update.

**Comment by BeaconBrigade** [comment]
@arkadijs I think I've finally fixed it with 1da990953ac5abf189b6833724706acaae203fe4 tagged v0.3.2 or [this release](https://github.com/BeaconBrigade/package-json-version/releases/tag/v0.3.2)

**Comment by arkadijs** [comment]
Thanks, 0.3.2 works.
